#!/bin/bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

##############################################################
# MAC-Specifi Aliases 
##############################################################

alias alcoreapps='open /System/Library/CoreServices/Applications'
alias alkilltouchbaragent='sudo pkill TouchBarServer'
alias alnameservers="scutil --dns | grep 'nameserver\[[0-9]*\]'"
alias alportsinuse='lsof -iTCP -sTCP:LISTEN -n -P'
alias alsay='say "cursus non est consumatus" --rate 120 -i -v Alice'
alias alusbinfo='system_profiler SPUSBDataType' # Only on Mac

