#!/usr/bin/env bash

PREVIOUSDIR=$PWD

#########################################
### TMUX Requires libevent
#########################################

# DOWNLOAD SOURCES FOR LIBEVENT AND MAKE AND INSTALL
cd /tmp
curl -LOk https://github.com/libevent/libevent/releases/download/release-2.1.8-stable/libevent-2.1.8-stable.tar.gz
tar -xf libevent-2.1.8-stable.tar.gz
cd libevent-2.1.8-stable
./configure --prefix=$HOME/.myfs/usr/local
make
make install

# DOWNLOAD SOURCES FOR TMUX AND MAKE AND INSTALL
cd /tmp
curl -LOk https://github.com/tmux/tmux/releases/download/3.1b/tmux-3.1b.tar.gz
tar -xf tmux-3.1b.tar.gz
cd tmux-3.1b
make distclean 
CFLAGS="-I$HOME/.myfs/usr/local/include" LDFLAGS="-L$HOME/.myfs/usr/local/lib -Wl,-rpath=$HOME/.myfs/usr/local/lib" ./configure --prefix=$HOME/.myfs/usr/local
make
make install

# open new shell and check tmux version
tmux -V
cd $PREVIOUSDIR
