#!/usr/bin/env bash
#
# yusr = yum + user; it's like 'pip install --user' but for yum
# yusr is a crude wrapper around yumdownloader, rpm2cpio and cpio
# It was developed within a docker centos8 image

### Check the prereq commands are available
function abort_install() {
    echo "${1:-Aborting install for unspecified reasons}"
    echo "This script relies on the admin installing 'yum-utils'"
    echo "If that isn't an option then, well, is it really worth it?"
    exit 1
}
command -v yumdownloader >/dev/null 2>&1 || abort_install "yumdownloader not found; exiting;"
command -v rpm2cpio >/dev/null 2>&1 || abort_install "rpm2cpio not found; exiting;"
command -v getopts >/dev/null 2>&1 || abort_install "getopts not found; exiting;"

### Setup dirs
[[ ! -d $HOME/.myfs/rpm ]] && mkdir -p $HOME/.myfs/rpm

###############################################################
### Parse commands, args, etc.
###############################################################

### Parse options to the `yusr` command
### See: https://sookocheff.com/post/bash/parsing-bash-script-arguments-with-shopts/
while getopts ":h" opt; do
    case ${opt} in
    h)
        echo "Usage:"
        echo "yusr -h                   Display this help message."
        echo "yusr install <package>    Install <package>."
        echo "yusr search <package>     Search <package>."
        exit 0
        ;;
    \?)
        echo "Invalid Option: -$OPTARG" 1>&2
        exit 1
        ;;
    esac
done
shift $((OPTIND - 1))
subcommand=$1
shift # Remove 'yusr' from the argument list

### Parse options to the install sub command
case "$subcommand" in
install)
    package=$1
    shift # Remove 'install' from the argument list

    ### Logic to download and extract rpm files
    prev_dir=$PWD
    cd "$HOME/.myfs/rpm"
    ### Make sure filesystem is the first thing to be downloaded
    echo "$HOME/.myfs/rpm/filesystem-3.2-25.el7.x86_64.rpm" >/tmp/temprpmfiles.txt
    ### Wrap around yumdownloader to download rpm's for package and dependencies
    ### NOTE: in a more sophisticated version, we'd save output to file
    ### so we know what rpms just got downloaded and then only unpack THOSE
    yumdownloader --resolve --alldeps $package
    ### Loop through rpms and extract filesystem to .myfs
    for FILE in $HOME/.myfs/rpm/*; do
        chmod -R u+w .
        echo ">>> $FILE"
        rpm2cpio "$FILE" | cpio -id --no-preserve-owner
        # Make sure we don't create anything we can't edit later
        chmod -R u+w .
    done
    cd $prev_dir
    ;;
search)
    package=$1
    shift # Remove 'search' from the argument list
    yum search $package
    ;;
esac
