#!/bin/bash
#
# Completes installation of YouCompleteMe Vundle Plugin.
# Needed because ycm needs cmake for installation,
# and this may not be available on your machine.

### Prelims
cxx=$(which g++)

### Confirm some prereqs
[[ ! -d $HOME/.vim/bundle ]] && echo "$HOME/.vim/bundle not found" && exit 1
command -v python3 >/dev/null 2>&1 || (echo "python3 not found" && exit 1)

### If cmake doesn't exist, install it with python3
if ! $(command -v cmake >/dev/null 2>&1); then
    command -v pip3 >/dev/null 2>&1 || (echo "pip3 not found" && exit 1)
    python3 -m pip install --user cmake
fi

### If Ubuntu18, then we need to install g++-8
if _is_ubuntu18 then;
    ### Check if g++-8 is installed
    if ! $(command -v g++-8 >/dev/null 2&>1 ); then
        cxx=$(which g++-8)
    elif _is_sudoer;then
        sudo apt install -y g++-8
        cxx=$(which g++-8)
    else
        echo -e "You are on Ubuntu18 without g++-8 or sudo permissions"
        exit 1
    fi
fi

### Rerun ycm-install process manually
previous_dir=$PWD
cd $HOME/.vim/bundle/YouCompleteMe
git pull origin master
git submodule update --init --recursive
CXX=$cxx python3 install.py --all

echo -e "echo '''\033[31m
====================================
YouCompleteMe Installation Finalized
====================================\n\033[37m''';
"
cd $previous_dir
