#!/bin/bash
#
# Install ncurses to ~/.myfs from source

previous_dir=$PWD
cd /tmp
curl -o ncurses.tar.gz http://ftp.gnu.org/pub/gnu/ncurses/ncurses-6.2.tar.gz
tar -xzvf ncurses.tar.gz
cd ncurses-6.2
make distclean >/dev/null 2>&1
./configure --prefix=$HOME/.myfs/usr/local
make
make install
cd $previous_dir
