#!/usr/bin/env bash

previous_dir=$PWD

### Install ncurses

if [[ $1 == '--with-ncurses' ]]; then
    echo "Installing ncurses to .myfs"
    sleep 2
    _install_ncurses
else
    echo "Skipping ncurses from source..."
    sleep 2
fi

### Install zsh
cd /tmp
curl -Lo zsh.tar.gz https://sourceforge.net/projects/zsh/files/latest/download
[[ ! -d zsh ]] && mkdir zsh
tar xf zsh.tar.gz -C zsh --strip-components 1
cd zsh
CPPFLAGS="-I$HOME/.myfs/local/include" LDFLAGS="-L$HOME/.myfs/local/lib" ./configure --prefix="$HOME/.myfs/local"
make -j
make install

### install ohmyzsh
cd $HOME
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

### Add autosuggestions git repo
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

git clone https://github.com/lukechilds/zsh-nvm.git ~/.zsh-nvm


### install powerlevel10k
cd $HOME
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k

### Fix the fact that installing these will mess with your committed .rc files
_replace_dotrc_files

cd $previous_dir
