#!/usr/bin/env bash

previous_dir=$PWD

### Install ncurses

if [[ $1 == '--with-ncurses' ]]; then
  echo "Installing ncurses to .myfs"
  sleep 2
  _install_ncurses
else
  echo "Skipping ncurses from source..."
  sleep 2
fi

### Install zsh
cd /tmp
curl -Lo zsh.tar.gz https://sourceforge.net/projects/zsh/files/latest/download
[[ ! -d zsh ]] && mkdir zsh
tar xf zsh.tar.gz -C zsh --strip-components 1
cd zsh
CPPFLAGS="-I$HOME/.myfs/local/include" LDFLAGS="-L$HOME/.myfs/local/lib" ./configure --prefix="$HOME/.myfs/local"
make -j
make install

### Install ohmyzsh, etc.
$HOME/.myconfig/COMMON/.bin/_install_ohmyzsh

cd $previous_dir

###
