#!/usr/bin/env bash

### Replace .rc config files
sleep 3
echo -e """${RED}
    ========
    WARNING!
    ========

    If any of the following files exist then they will get moved to ${CYA}~/.myconfig/redundant${WHI}:

    .bashrc
    .p10k.zsh
    .tmux.conf
    .vimrc
    .zshrc

    ${WHI}"""

### Move old config files to myconfig/redundant
[[ ! -d $HOME/.myconfig/redundant ]] && mkdir $HOME/.myconfig/redundant
[[ -f $HOME/.bashrc ]] &&
    cp $HOME/.bashrc $HOME/.myconfig/redundant/.bashrc-original
[[ -f $HOME/.p10k.zsh ]] &&
    cp $HOME/.p10k.zsh $HOME/.myconfig/redundant/.p10k.zsh-original
[[ -f $HOME/.tmux.conf ]] &&
    cp $HOME/.tmux.conf $HOME/.myconfig/redundant/.tmux.conf-original
[[ -f $HOME/.vimrc ]] &&
    cp $HOME/.vimrc $HOME/.myconfig/redundant/.vimrc-original
[[ -f $HOME/.zshrc ]] &&
    cp $HOME/.zshrc $HOME/.myconfig/redundant/.zshrc-original

### Create symlinks from myconfig to ~
ln -s $HOME/.myconfig/.bashrc $HOME/.bashrc
ln -s $HOME/.myconfig/.p10k.zsh $HOME/.p10k.zsh
ln -s $HOME/.myconfig/.tmux.conf $HOME/.tmux.conf
ln -s $HOME/.myconfig/.vimrc $HOME/.vimrc
ln -s $HOME/.myconfig/.zshrc $HOME/.zshrc
