#!/bin/bash
#
# Installs all the vundle plugins in a background subprocess


### Confirm some prereqs
hash vim >/dev/null 2>&1 || (echo "vim not found" && return 1)

### Clone/update vundle repo
if [[ ! -d $HOME/.vim/bundle/Vundle.vim ]]; then
    # If Vundle dir does exist then clone it
    git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
else
    # If Vundle dir exists, update it
    cd $HOME/.vim/bundle/Vundle.vim
    git fetch origin
    git checkout master
    git reset --hard origin/master
fi

### Install vundle plugins 
echo "Installing vundle plugins..."
vim -E -N +PluginInstall +qall

### Double check complete installation of ycm
_complete_ycm_installation


